application: festive-ally-585
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"

- name: MySQLdb
  version: "latest"

- name: endpoints
  version: 1.0

- name: PIL
  version: "latest"

- name: webapp2
  version: latest

# The pycrypto library is used for OAuth 2, and is also a requirement for
# APIs that wish to authenticate users.
- name: pycrypto
  version: latest

handlers:
#- url: /googleea214a6cce8d7412.html
#  static_files: static/googleea214a6cce8d7412.html
#  upload: static/googleea214a6cce8d7412.html

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js
  http_headers:
    Access-Control-Allow-Origin: https://festive-ally-585.appspot.com

- url: /lib
  static_dir: static/lib

#- url: /partials
#  static_dir: static/partials

- url: /stylesheets
  static_dir: static/stylesheets
  http_headers:
    Access-Control-Allow-Origin: https://festive-ally-585.appspot.com

#- url:/index.html
#  static_files:static/index.html
#  upload:static/index.html

- url: /taskman/.*
  script: main.cron

- url: /.*
  script: main.application

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'Django_AppEngine.settings'
