'''
Created on 10-01-2015

@author: carriagadad
'''
from google.appengine.ext import ndb
class Events(ndb.Model):
    events_id=ndb.StringProperty(indexed=True,required=True)
    events_title=ndb.StringProperty(indexed=True,required=True)
    events_description=ndb.StringProperty(indexed=False,required=False)
    events_latitude=ndb.StringProperty(indexed=True,required=False)
    events_longitude=ndb.StringProperty(indexed=True,required=False)
    events_start=ndb.DateTimeProperty(indexed=True,required=False)
    events_finish=ndb.DateTimeProperty(indexed=True,required=False)
    events_type=ndb.StringProperty(required=True,choices=set(['timer','countdown']))
    fk_user_creator=ndb.StringProperty(indexed=True,required=True)
    events_enable=ndb.IntegerProperty()
    events_delete=ndb.IntegerProperty()
    events_language=ndb.StringProperty(indexed=True,required=False)
    events_country=ndb.StringProperty(indexed=True,required=False)
    events_velocity=ndb.IntegerProperty()
    events_image=ndb.StringProperty(indexed=False,required=False)
    events_level=ndb.StringProperty(indexed=True,required=True,choices=set(['Normal','Sponsored']))
    events_title_id=ndb.StringProperty(indexed=True,required=True)
    events_skins=ndb.StringProperty(indexed=True,required=True,choices=set(['skin1','skin2','skin3','skin4']))
    events_fb_event_id=ndb.StringProperty(indexed=True,required=False)
    events_date_creation=ndb.DateTimeProperty(required=False,auto_now_add=True)
    events_date_modification=ndb.DateTimeProperty(required=False,auto_now=True)
    hashtags=ndb.StringProperty(indexed=False,required=False)
    events_cc=ndb.StringProperty(indexed=True,required=False)
    events_ip=ndb.StringProperty(indexed=True,required=False)
    events_fb_ids=ndb.BlobProperty()
    events_msg=ndb.StringProperty(indexed=False,required=False)
    events_img_str=ndb.StringProperty(indexed=False,required=False)
    events_sort=ndb.StringProperty(indexed=True,required=False)
    events_image_stamp=ndb.StringProperty(indexed=False,required=True)
class Users(ndb.Model):
    users_id=ndb.StringProperty(indexed=True,required=True)
    users_name=ndb.StringProperty(indexed=True,required=True)
    users_name_id=ndb.StringProperty(indexed=True,required=True)
    users_lastname=ndb.StringProperty(indexed=True,required=True)
    users_firstname=ndb.StringProperty(indexed=True,required=True)
    users_email=ndb.StringProperty(indexed=True,required=True)
    users_password=ndb.StringProperty(indexed=True,required=True)
    users_fb_id=ndb.StringProperty(indexed=True,required=False)
    users_path_local_avatar=ndb.StringProperty(indexed=False,required=False)
    users_path_web_avatar=ndb.StringProperty(indexed=True,required=False)
    users_time_zone=ndb.StringProperty(indexed=True,required=False)
    fk_users_type=ndb.StringProperty(indexed=True,required=True)
    users_delete=ndb.IntegerProperty()
    users_birthday=ndb.DateTimeProperty(indexed=True,required=False)
    users_sex=ndb.StringProperty(indexed=True,required=False,choices=set(['Male','Female']))
    users_hashtags=ndb.StringProperty(indexed=False,required=False)
    users_date_joined=ndb.DateTimeProperty(required=False,auto_now_add=True)
    users_locale=ndb.StringProperty(indexed=True,required=False)
    users_middle_name=ndb.StringProperty(indexed=True,required=False)
    users_is_location_enable=ndb.IntegerProperty()
    users_is_nearby_enable=ndb.IntegerProperty()
class UsersFollowsEvents(ndb.Model):
    users_follows_events_id=ndb.StringProperty(indexed=True,required=True)
    users_follows_events_subscription_date=ndb.DateTimeProperty(required=False,auto_now_add=True)
    fk_users=ndb.StringProperty(indexed=True,required=True)
    fk_events=ndb.StringProperty(indexed=True,required=True)
class UsersWritesComments(ndb.Model):
    users_writes_comments_id=ndb.StringProperty(indexed=True,required=True)
    users_writes_comments_content=ndb.StringProperty(indexed=False,required=True)
    fk_users=ndb.StringProperty(indexed=True,required=True)
    fk_events=ndb.StringProperty(indexed=True,required=True)
    users_writes_comments_delete=ndb.IntegerProperty()
class EventsQueue(ndb.Model):
    events_id=ndb.StringProperty(indexed=True,required=True)
    events_title=ndb.StringProperty(indexed=True,required=True)
    events_title_id=ndb.StringProperty(indexed=True,required=True)
    fk_user_creator=ndb.StringProperty(indexed=True,required=True)
    events_finish=ndb.DateTimeProperty(indexed=True,required=True)
    events_alert_minutes=ndb.IntegerProperty()